name: Lint yaml
on: push               # yamllint disable-line rule:truthy
env:
  CI: true

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v1
        with:
          file_or_dir: .github/workflows _config.yml
          config_file: .github/linters/.yamllint
